language: python
python:
  - "3.9"

services:
  - ranking

before_script: pip install -r requirements.txt

script:
  - python -m ranking init --db_path=./ranking.json && pytest tests && black ranking tests